version: '3.3'
services:
        mongo:
                image: mongo:latest
                container_name: mongo
                volumes:
                - type: volume
                  source: persist
                  target: /data/db
        mongo-service:
                build: ./mongo-service
                image: samvivers/mongo-service:v${BUILD_NUMBER}
                container_name: mongo-service
                depends_on:
                - mongo
        secret-service:
                build: ./secret-service
                image: samvivers/secret-service:v${BUILD_NUMBER}
                container_name: secret-service
                depends_on:
                - mongo-service
        email-service:
                build: ./email-service
                image: samvivers/email-service:v${BUILD_NUMBER}
                container_name: email-service
                environment:
                - GMAIL_USER=ilovedocker123@gmail.com
                - GMAIL_PASS=ilovedocker1!
                - SERVICE_NAME=emailer
                depends_on:
                - mongo-service
                - aes-encryption-service
        account-service:
                build: ./account-service
                image: samvivers/account-service:v${BUILD_NUMBER}
                container_name: account-service
                depends_on:
                - secret-service
                - mongo-service
        aes-encryption-service:
                build: ./aes-encryption-service
                image: samvivers/aes-encryption-service:v${BUILD_NUMBER}
                container_name: aes-encryption-service
        session-token-service:
                build: ./session-token-service
                image: samvivers/session-token-service:v${BUILD_NUMBER}
                container_name: session-token-service
                depends_on:
                - aes-encryption-service
                - mongo-service
        dashboard-service:
                build: ./dashboard-service
                image: samvivers/dashboard-service:v${BUILD_NUMBER}
                container_name: dashboard-service
                depends_on:
                - account-service
        dashboard-client:
                build: ./dashboard-client
                image: samvivers/dashboard-client:v${BUILD_NUMBER}
                container_name: dashboard-client
        authentication-service:
                build: ./authentication-service
                image: samvivers/authentication-service:v${BUILD_NUMBER}
                container_name: authentication-service
                environment:
                - ACTIVATION_LINK=http://${IP}/authentication/api/activate
                depends_on:
                - account-service
                - email-service
                - session-token-service
        authentication-client:
                build: ./authentication-client
                image: samvivers/authentication-client:v${BUILD_NUMBER}
                container_name: authentication-client
        gateway:
                build: ./gateway
                image: samvivers/gateway:v${BUILD_NUMBER}
                container_name: gateway
                ports:
                - target: 80
                  published: 80
                  protocol: tcp
                depends_on:
                - dashboard-client
                - dashboard-service
                - authentication-service
                - authentication-client
        role-service:
                build: ./role-service
                image: samvivers/role-service:v${BUILD_NUMBER}
                container_name: role-service
        group-service:
                build: ./group-service
                image: samvivers/group-service:v${BUILD_NUMBER}
                container_name: group-service
                        
volumes:
        persist: 
